#!/bin/bash

#This is the program that creates some frame around the word user type in

word=$1
len=${#word}


for (( i=0; i<100; i++ ))
	do
		echo -n "*"
	done

echo " "


echo -n "*"
for (( i=0; i<98; i++ ))
	do
		echo -n " "
	done
echo "*"


echo -n "*"
echo $word

for (( i=0; i<98; i++ ))
	do
		echo -n " "
	done
echo "*"


echo -n "*"
for (( i=0; i<98; i++ ))
	do
		echo -n " "
	done
echo "*"


for (( i=0; i<100; i++ ))
	do
		echo -n "*"
	done


		
