#!/bin/bash

#This file test the first success criterion, namely,
#A car can be created and stored in the database

#step1: create a car using the script create
bash ../create TXM301 issan red 9

#step 2: check that the livense file.txt was created
if [ -f "../Database/TXM301.txt" ]; then
	echo "test one: a txt file was created inside the database: passed"

else
	echo "test one: Error, file not found: not passed"
fi

#step 3: Check that the car was added to the main file
cat Database/maincarfile.txt
lastline=$( tail -n 1 Database/maincarfile.txt )
if [ "TXM301 nissan Red 9" == $lastline ]; then
	echo "Test two: Record was entered correctly: Passed"
else
	echo "Test two: Failed"
fi

