#!/bin/bash

#This file creates the folder structure for the
#minimal Car Rental App

echo "Starting the installation"
echo "Default install path is /home/keitaromae/Desktop"
echo "Press Enter to continue installation, if you"
echo "want to change install path press x  "

read sel

#checking what user eneted
if [[ ($sel == x) ]];then
    echo "Enter installation path, then press Enter"
    read loc

    #moving to the desired location
    cd $loc
    echo "moving to $loc"

else
  #moving to default location
  cd ~/Desktop
fi

#Create App folder
mkdir carrentalapp

#move to created folder
cd carrentalapp

#create for database and scripts
mkdir Database
mkdir scripts

echo "structure created successfully"
